#!/usr/bin/env python3
"""Generate the reviewed primitive Live DTO subset; native adoption is deferred.

Fail closed on unsupported shapes. These DTOs describe wire fields, not runtime
validation, discriminated-union decoding or feature availability.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('LiveWebRTCTransport', 'LiveKitRoomTransport', 'LiveCapabilities', 'HostedHelperUsage')


def render(contract):
    schemas = {name: contract['components']['schemas'][name] for name in NAMES}
    digest = hashlib.sha256(json.dumps(schemas, sort_keys=True).encode()).hexdigest()
    header = f'// Generated by scripts/generate_live_dtos.py; do not edit.\n// Selected schema SHA256: {digest}\n'
    ts, swift, kotlin = [header], [header, 'import Foundation\n'], [header, 'package chat.mural.contracts\n\nimport kotlinx.serialization.Serializable\n']
    types = {'string': ('string', 'String', 'String'), 'integer': ('number', 'Int64', 'Long'), 'boolean': ('boolean', 'Bool', 'Boolean')}
    for name, schema in schemas.items():
        if schema.get('type') != 'object' or schema.get('additionalProperties') is not False:
            raise ValueError(f'Unsupported object {name}')
        fields = []
        for key, field in schema['properties'].items():
            field = dict(field)
            if 'type' not in field and 'const' in field:
                field['type'] = 'boolean' if isinstance(field['const'], bool) else 'string' if isinstance(field['const'], str) else None
            if not key.isidentifier() or field.get('type') not in types or any(k in field for k in ('$ref', 'oneOf', 'anyOf', 'allOf')):
                raise ValueError(f'Unsupported field {name}.{key}')
            fields.append((key, field, key not in schema.get('required', [])))
        ts.append(f'export type {name}DTO = {{')
        swift.append(f'public struct {name}DTO: Codable, Sendable {{')
        kotlin.append(f'@Serializable\ndata class {name}DTO(')
        for index, (key, field, optional) in enumerate(fields):
            t, s, k = types[field['type']]
            if 'const' in field:
                t = json.dumps(field['const'])
            elif 'enum' in field:
                t = ' | '.join(json.dumps(value) for value in field['enum'])
            ts.append(f'  {key}{"?" if optional else ""}: {t};')
            swift.append(f'    public let {key}: {s}{"?" if optional else ""}')
            kotlin.append(f'    val {key}: {k}{"? = null" if optional else ""}{"," if index + 1 < len(fields) else ""}')
        ts.append('};\n'); swift.append('}\n'); kotlin.append(')\n')
    return {'live.ts': '\n'.join(ts), 'LiveDTOs.swift': '\n'.join(swift), 'LiveDTOs.kt': '\n'.join(kotlin)}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    contract = json.loads((ROOT / 'shared/contracts/mural-api.openapi.json').read_text())
    target = ROOT / 'shared/contracts/generated'
    for name, text in render(contract).items():
        path = target / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f'Generated DTO drift: {path.relative_to(ROOT)}')
        else:
            target.mkdir(parents=True, exist_ok=True)
            path.write_text(text)


if __name__ == '__main__':
    main()
