#!/usr/bin/env python3
"""Generate the reviewed Live wire DTO graph; runtime client adoption is deferred.

Fail closed on unsupported shapes. These DTOs describe wire fields, not runtime
validation or feature availability. Native union codecs preserve wire presence.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('LiveWebRTCTransport', 'LiveKitRoomTransport', 'LiveCapabilities', 'HostedHelperUsage')
TS_NAMES = NAMES + ('LiveTransport', 'LiveSession', 'LiveSessionStatus', 'CurrentLiveSession',
                    'LiveHistoryMessage', 'LiveSessionCreateRequest', 'HostedHelperResult', 'HostedHelperStreamEvent', 'ErrorResponse')


def ts_type(schema):
    """Wire types only; JSON Schema refinements remain runtime validation."""
    if '$ref' in schema:
        prefix = '#/components/schemas/'
        reference = schema['$ref']
        if not reference.startswith(prefix) or reference[len(prefix):] not in TS_NAMES:
            raise ValueError(f'Unsupported reference {reference}')
        return reference[len(prefix):] + 'DTO'
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(value) for value in schema['enum'])
    for keyword in ('oneOf', 'anyOf'):
        if keyword in schema:
            if not schema[keyword]:
                raise ValueError('Empty union')
            return ' | '.join('(' + ts_type(branch) + ')' for branch in schema[keyword])
    if 'allOf' in schema:
        raise ValueError('Conditional/intersection schemas require explicit review')
    kind = schema.get('type')
    if isinstance(kind, list):
        return ' | '.join(ts_type({**schema, 'type': member}) for member in kind)
    if kind in ('string', 'integer', 'number', 'boolean', 'null'):
        return {'integer': 'number'}.get(kind, kind)
    if kind == 'array':
        return 'Array<' + ts_type(schema['items']) + '>'
    if kind == 'object' and schema.get('additionalProperties') is False:
        fields = []
        for key, value in schema.get('properties', {}).items():
            optional = '' if key in schema.get('required', []) else '?'
            fields.append(json.dumps(key) + optional + ': ' + ts_type(value) + ';')
        return '{ ' + ' '.join(fields) + ' }'
    raise ValueError(f'Unsupported TS schema shape: {kind}')


def render_ts(contract):
    schemas = {name: contract['components']['schemas'][name] for name in TS_NAMES}
    digest = hashlib.sha256(json.dumps(schemas, sort_keys=True).encode()).hexdigest()
    lines = ['// Generated by scripts/generate_live_dtos.py; do not edit.',
             f'// Selected schema SHA256: {digest}',
             '// Wire types only, not JSON Schema validators.']
    for name, schema in schemas.items():
        lines.append(f'export type {name}DTO = {ts_type(schema)};')
    return '\n'.join(lines) + '\n'


def render(contract):
    # Imports work both when invoked as a script and as a unittest module.
    try:
        from .live_native_codegen import render_native
    except ImportError:
        from live_native_codegen import render_native
    schemas = {name: contract['components']['schemas'][name] for name in TS_NAMES}
    digest = hashlib.sha256(json.dumps(schemas, sort_keys=True).encode()).hexdigest()
    header = f'// Generated by scripts/generate_live_dtos.py; do not edit.\n// Selected schema SHA256: {digest}\n'
    swift, kotlin = render_native(schemas, TS_NAMES, header)
    return {'live.d.ts': render_ts(contract), 'LiveDTOs.swift': swift, 'LiveDTOs.kt': kotlin}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    contract = json.loads((ROOT / 'shared/contracts/mural-api.openapi.json').read_text())
    target = ROOT / 'shared/contracts/generated'
    for name, text in render(contract).items():
        path = target / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f'Generated DTO drift: {path.relative_to(ROOT)}')
        else:
            target.mkdir(parents=True, exist_ok=True)
            path.write_text(text)


if __name__ == '__main__':
    main()
