#!/usr/bin/env python3
"""Generate the reviewed primitive Live DTO subset; native adoption is deferred.

Fail closed on unsupported shapes. These DTOs describe wire fields, not runtime
validation, discriminated-union decoding or feature availability.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('LiveWebRTCTransport', 'LiveKitRoomTransport', 'LiveCapabilities', 'HostedHelperUsage')
TS_NAMES = NAMES + ('LiveTransport', 'LiveSession', 'LiveSessionStatus', 'CurrentLiveSession',
                    'LiveHistoryMessage', 'LiveSessionCreateRequest', 'HostedHelperResult', 'HostedHelperStreamEvent', 'ErrorResponse')


def ts_type(schema):
    """Wire types only; JSON Schema refinements remain runtime validation."""
    if '$ref' in schema:
        prefix = '#/components/schemas/'
        reference = schema['$ref']
        if not reference.startswith(prefix) or reference[len(prefix):] not in TS_NAMES:
            raise ValueError(f'Unsupported reference {reference}')
        return reference[len(prefix):] + 'DTO'
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(value) for value in schema['enum'])
    for keyword in ('oneOf', 'anyOf'):
        if keyword in schema:
            if not schema[keyword]:
                raise ValueError('Empty union')
            return ' | '.join('(' + ts_type(branch) + ')' for branch in schema[keyword])
    if 'allOf' in schema:
        raise ValueError('Conditional/intersection schemas require explicit review')
    kind = schema.get('type')
    if isinstance(kind, list):
        return ' | '.join(ts_type({**schema, 'type': member}) for member in kind)
    if kind in ('string', 'integer', 'number', 'boolean', 'null'):
        return {'integer': 'number'}.get(kind, kind)
    if kind == 'array':
        return 'Array<' + ts_type(schema['items']) + '>'
    if kind == 'object' and schema.get('additionalProperties') is False:
        fields = []
        for key, value in schema.get('properties', {}).items():
            optional = '' if key in schema.get('required', []) else '?'
            fields.append(json.dumps(key) + optional + ': ' + ts_type(value) + ';')
        return '{ ' + ' '.join(fields) + ' }'
    raise ValueError(f'Unsupported TS schema shape: {kind}')


def render_ts(contract):
    schemas = {name: contract['components']['schemas'][name] for name in TS_NAMES}
    digest = hashlib.sha256(json.dumps(schemas, sort_keys=True).encode()).hexdigest()
    lines = ['// Generated by scripts/generate_live_dtos.py; do not edit.',
             f'// Selected schema SHA256: {digest}',
             '// Wire types only, not JSON Schema validators.']
    for name, schema in schemas.items():
        lines.append(f'export type {name}DTO = {ts_type(schema)};')
    return '\n'.join(lines) + '\n'


def render(contract):
    schemas = {name: contract['components']['schemas'][name] for name in NAMES}
    digest = hashlib.sha256(json.dumps(schemas, sort_keys=True).encode()).hexdigest()
    header = f'// Generated by scripts/generate_live_dtos.py; do not edit.\n// Selected schema SHA256: {digest}\n'
    ts, swift, kotlin = [header], [header, 'import Foundation\n'], [header, 'package chat.mural.contracts\n\nimport kotlinx.serialization.Serializable\n']
    types = {'string': ('string', 'String', 'String'), 'integer': ('number', 'Int64', 'Long'), 'boolean': ('boolean', 'Bool', 'Boolean')}
    for name, schema in schemas.items():
        if schema.get('type') != 'object' or schema.get('additionalProperties') is not False:
            raise ValueError(f'Unsupported object {name}')
        fields = []
        for key, field in schema['properties'].items():
            field = dict(field)
            if 'type' not in field and 'const' in field:
                field['type'] = 'boolean' if isinstance(field['const'], bool) else 'string' if isinstance(field['const'], str) else None
            if not key.isidentifier() or field.get('type') not in types or any(k in field for k in ('$ref', 'oneOf', 'anyOf', 'allOf')):
                raise ValueError(f'Unsupported field {name}.{key}')
            fields.append((key, field, key not in schema.get('required', [])))
        ts.append(f'export type {name}DTO = {{')
        swift.append(f'public struct {name}DTO: Codable, Sendable {{')
        kotlin.append(f'@Serializable\ndata class {name}DTO(')
        for index, (key, field, optional) in enumerate(fields):
            t, s, k = types[field['type']]
            if 'const' in field:
                t = json.dumps(field['const'])
            elif 'enum' in field:
                t = ' | '.join(json.dumps(value) for value in field['enum'])
            ts.append(f'  {key}{"?" if optional else ""}: {t};')
            swift.append(f'    public let {key}: {s}{"?" if optional else ""}')
            kotlin.append(f'    val {key}: {k}{"? = null" if optional else ""}{"," if index + 1 < len(fields) else ""}')
        ts.append('};\n'); swift.append('}\n'); kotlin.append(')\n')
    return {'live.d.ts': render_ts(contract), 'LiveDTOs.swift': '\n'.join(swift), 'LiveDTOs.kt': '\n'.join(kotlin)}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    contract = json.loads((ROOT / 'shared/contracts/mural-api.openapi.json').read_text())
    target = ROOT / 'shared/contracts/generated'
    for name, text in render(contract).items():
        path = target / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f'Generated DTO drift: {path.relative_to(ROOT)}')
        else:
            target.mkdir(parents=True, exist_ok=True)
            path.write_text(text)


if __name__ == '__main__':
    main()
